from datetime import datetime

from src.audit.models import AuditRecord, AuditStatus, ReviewDecision
from src.audit.queue import AuditQueue


def make_audit_record():
    return AuditRecord(
        audit_id="",  # will be generated by queue
        timestamp=datetime.now(),
        created_at=datetime.now(),
        user_query="What was revenue?",
        claim="Revenue was $42.8B",
        verification_status="VERIFIED",
        verification_reason="numeric_match",
        risk_level="LOW",
        risk_assessment="some risk",
        evidence=[],
        document_id="doc1",
        document_sha256="abc123",
        page_number=3,
        confidence_score=0.9,
        risk_score=0.1,
        triggers=[],
        verification_results=[],
    )


def test_enqueue_generates_unique_ids():
    queue = AuditQueue()
    record1 = make_audit_record()
    record2 = make_audit_record()
    id1 = queue.enqueue(record1)
    id2 = queue.enqueue(record2)
    assert id1 != id2
    assert record1.audit_id == id1
    assert record2.audit_id == id2


def test_get_pending():
    queue = AuditQueue()
    record1 = make_audit_record()
    record2 = make_audit_record()
    queue.enqueue(record1)
    queue.enqueue(record2)
    pending = queue.get_pending()
    assert len(pending) == 2
    # after starting review, not pending anymore
    queue.start_review(record1.audit_id, "reviewer")
    pending = queue.get_pending()
    assert len(pending) == 1
    assert pending[0].audit_id == record2.audit_id


def test_get_by_id():
    queue = AuditQueue()
    record = make_audit_record()
    audit_id = queue.enqueue(record)
    fetched = queue.get_by_id(audit_id)
    assert fetched is not None
    assert fetched.audit_id == audit_id
    assert fetched.user_query == "What was revenue?"


def test_resolve_item():
    queue = AuditQueue()
    record = make_audit_record()
    audit_id = queue.enqueue(record)
    assert queue.start_review(audit_id, "reviewer") is True
    assert queue.resolve(audit_id, ReviewDecision.APPROVED, "Looks good") is True
    resolved = queue.get_by_id(audit_id)
    assert resolved.status == AuditStatus.RESOLVED
    assert resolved.review_decision == ReviewDecision.APPROVED
    assert resolved.review_notes == "Looks good"


def test_invalid_state_transition_rejected():
    queue = AuditQueue()
    record = make_audit_record()
    audit_id = queue.enqueue(record)
    # Cannot resolve without starting review
    assert queue.resolve(audit_id, ReviewDecision.APPROVED, "") is False
    # Cannot start review on non-existing
    assert queue.start_review("nonexistent", "reviewer") is False
    # Cannot start review twice
    assert queue.start_review(audit_id, "reviewer") is True
    assert queue.start_review(audit_id, "another") is False


def test_evidence_preserved():
    queue = AuditQueue()
    record = make_audit_record()
    record.evidence = [{"chunk_id": "chunk1", "text": "Revenue ..."}]
    queue.enqueue(record)
    fetched = queue.get_by_id(record.audit_id)
    assert fetched.evidence == [{"chunk_id": "chunk1", "text": "Revenue ..."}]